### ISSUE TITLE
Unable to build iOS using with expo using eas build

### ISSUE THREAD

**Issue by ribbonhood** [wl-online-payments-direct/sdk-client-reactnative#2]
I'm unable to build on ios and keep getting the error
`error: Multiple commands produce '/Users/expo/Library/Developer/Xcode/DerivedData/myapp/Build/Intermediates.noindex/ArchiveIntermediates/myapp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/onlinepayments_sdk_client_reactnative.framework/Headers/OnlinePaymentsKit-Swift.h'`

**Comment by worldline-direct-support-team** [comment]
Hi ribbonhood, 

Can you please explain your issue in more details? Are you trying to build this code or you are building your code that references this package?

Sincerely,
Worldline Support Team

**Comment by ribbonhood** [comment]
I'm building code that uses this package in react native, using expo, but we get this error when building for the ios version of the app. We managed to get around it by doing `use_frameworks! :linkage => :static` and we're not getting any errors but haven't yet tested whether the library actually works

**Comment by worldline-direct-support-team** [comment]
Hi ribbonhood,

That might not work since currently, our ios version is included as xcframework (from Swift build), not as a pod, which you can see in the `onlinepayments-sdk-client-reactnative.podspec` file of the library. This will change in the future when some issues with CocoaPods are resolved on their side.

Anyhow, let us know if the library works as expected with the change you did.

Sincerely,
Worldline Support Team

**Comment by ribbonhood** [comment]
Library works as expected so I'll close the issue
